- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no
  environment:
     GCE_PROJECT: 
     GCE_EMAIL: 
     GCE_CREDENTIALS_FILE_PATH: 
     GCE_INI_PATH: 
     PYTHONPATH: /usr/local/lib/python2.7/site-packages/

  vars:
    service_account_email: 
    credentials_file: 
    project_id: 
    machine_type: n1-standard-1
    image: debian-9

  tasks:

   - name: Launch instances
     gce:
         instance_names: 
         zone: us-central1-a
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
         service_account_email: "{{ service_account_email }}"
         credentials_file: "{{ credentials_file }}"
         project_id: "{{ project_id }}"
         state: present
     register: gce
   - name: Create Firewall Rule of allowing 8764 port for Fusion server
     gce_net:
        name: default
        fwname: 
        allowed: tcp:8764
        state: "present"
   - name: Save host data
     add_host:
         hostname: "{{ item.public_ip }}"
         groupname: gceinstancesips
     loop: "{{ gce.instance_data }}"
   - name: SSH into the system
     wait_for:
         delay: 1
         host: "{{ item.public_ip }}"
         port: 22
         state: started
         timeout: 30
     loop: "{{ gce.instance_data }}" 
   
- name: Install apps on the new instances
  hosts: gceinstancesips
  connection: ssh
  sudo: true


  tasks:

   - name: Install httpd
     package:
        name: apache2
        state: present
   - name: Copy html
     copy:
        src: ~/Desktop/.../index.html
        dest: /var/www/html/indx.html
   - name: Start the apache server
     service:
       name: apache2
       state: started
   - name: Install add-apt-repostory
     become: yes
     apt:
       name: software-properties-common
       state: latest
   - name: Copy oracle java jdk
     copy:
        src: ~/Desktop/.../jdk-8u172-linux-x64.tar.gz
        dest: /home/
   - name: Check if /opt/jdk already exist
     stat:
      path: /opt/jdk
     register: jdk_dir
   - name: Java installation command 1
     become: yes
     command: sudo mkdir /opt/jdk
     when: jdk_dir.stat.exists== False
   - name: Java installation command 2
     become: yes
     command: tar -zxf /home/siddhiparekh11/jdk-8u172-linux-x64.tar.gz -C /opt/jdk
   - name: Java installation command 3
     become: yes
     command: update-alternatives --install /usr/bin/java java /opt/jdk/jdk1.8.0_172/bin/java 100
   - name: Java installation command 4
     become: yes
     command: update-alternatives --install /usr/bin/javac javac /opt/jdk/jdk1.8.0_172/bin/javac 100
    
